version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.${ENV}
    container_name: fluxo-demissao
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .:/home/python/app